(function () {
  const rule = (metric, operator, value, description, extra = {}) => ({metric, operator, value, description, ...extra});
  const make = (code, chineseName, englishName, group, priority, triggerMode, triggerRules, coreCategories, traits, focus, distinctionRules, coreLogic, interpretationZh, interpretationEn, slogansZh, slogansEn, doNotSay, generationGuardrails, illustrationPrompt, extra = {}) => ({code, chineseName, englishName, group, priority, triggerMode, triggerRules, coreCategories, traits, focus, distinctionRules, coreLogic, interpretationZh, interpretationEn, slogansZh, slogansEn, doNotSay, generationGuardrails, illustrationPrompt, ...extra});
  window.MONEYBTI_PERSONA_RULES = [
    make("BKHZ","外卖包月户","Delivery Regular","food",40,"minimum",[
      rule("delivery_order_count_30d",">=",12,"近30天外卖订单不少于12次，平均每周不少于3次"),rule("delivery_share_of_dining",">=",0.5,"外卖支出占当月餐饮总支出不少于50%"),rule("delivery_active_weeks_30d",">=",3,"近30天至少3周出现外卖消费"),rule("delivery_meal_period_count",">=",2,"早餐、午餐、晚餐、夜宵覆盖至少2类"),rule("delivery_vs_ingredient_frequency",">",1,"外卖频次明显高于生鲜、食材采购频次")],
      ["外卖平台","配送型正餐","快餐","早餐","夜宵"],["便利至上","高频点单","时间优先","选择丰富","即时满足"],"高频、持续、配送型餐饮和明显的外卖使用习惯",["具体消费类别优先于消费渠道；外卖平台购买可识别茶饮时优先计入NCXM"],"高频外卖 × 持续出现 × 多用餐场景 × 高外卖依赖","你不是不会做饭，只是人生已经够忙，外卖软件成了第二食堂，总有一单正在路上。","Life is busy enough without another meal-planning side quest. Delivery apps are your second kitchen, with something nearly always on the way.",["厨房可以不开火，外卖软件不能没会员。"],["The kitchen can stay cold. Your delivery app can’t."],["购物狂","购物成瘾","剁手党","败家","乱花钱","冲动消费","管不住手"],["不把高频外卖解释为成瘾或缺乏自制力","不推断收入、健康、职业或生活能力","可围绕配送、骑手和选餐场景轻松表达"],"一只被外卖盒、手机订单和长收据围绕的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("NCXM","奶茶续命体","Milk Tea Lifeline","food",45,"minimum",[
      rule("fresh_tea_count_30d",">=",8,"近30天现制茶饮不少于8次"),rule("fresh_tea_active_weeks_30d",">=",3,"近30天至少3周出现茶饮消费"),rule("fresh_tea_weekly_average",">=",2,"平均每周茶饮消费不少于2次"),rule("same_tea_merchant_count_30d",">=",3,"至少一个茶饮品牌近30天重复消费不少于3次"),rule("tea_vs_snack_frequency",">",1,"现制茶饮频次明显高于其他零食甜品")],
      ["奶茶","新式茶饮","果茶","鲜奶茶"],["小额高频","快乐续杯","口味偏爱","日常仪式感","即时满足"],"消费频次 > 持续性 > 重复购买 > 消费金额",["外卖平台购买奶茶时按具体类别计入本人格，不因渠道同时过度提高BKHZ"],"高频茶饮 × 持续出现 × 小额消费 × 重复习惯","奶茶是生活里的小型快乐补给站，三分糖、少冰和加珍珠为普通的一天加上仪式感。","Milk tea is a small happiness refill: a familiar flavor and ritual that keeps appearing throughout ordinary days.",["生活可以偶尔有点苦，手里的奶茶必须是甜的。"],["Life can be bitter. Your milk tea doesn’t have to be."],["上瘾","成瘾","管不住嘴","不健康","发胖","浪费钱","没有自制力"],["不判断成瘾、体重、健康或饮食问题","不评价应该少喝","不推断压力、疲劳、收入","突出小额悦己和日常仪式"],"一只抱着超大杯珍珠奶茶的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("TDJ","探店雷达","Restaurant Radar","food",38,"minimum",[
      rule("experience_dining_count_30d",">=",8,"近30天线下体验型餐饮不少于8次"),rule("distinct_dining_merchants_30d",">=",6,"涉及至少6家不同餐饮商户"),rule("new_dining_merchant_share",">=",0.5,"当月首次出现的餐饮商户占比不少于50%"),rule("top_dining_merchant_share","<=",0.3,"单一餐饮商户次数不超过全部探店次数30%"),rule("experience_dining_share",">=",0.4,"体验型餐饮占线下餐饮不少于40%")],
      ["线下餐厅","咖啡馆","Brunch","甜品店","餐酒馆"],["尝鲜优先","新店雷达","口味探索","体验导向","低重复率"],"商户多样性、新店率和持续探索",["配送高频属于BKHZ","多品牌茶饮属于NCXM","同一家咖啡店高频不等于探店"],"线下体验型餐饮 × 多商户 × 高新店率 × 低重复率","你的美食地图不断更新，吃饭不只是解决一餐，更是在城市里解锁新坐标。","Your food map keeps getting new pins. Eating out is a small city adventure, including both hidden gems and funny misses.",["你的美食地图没有终点，只有下一个新坐标。"],["Same city, new table."],["贪吃","乱花钱","跟风","网红打卡","虚荣","不会过日子"],["不把尝新描述为跟风","不默认为了拍照或社交媒体","不评价餐饮支出或推断财富健康","突出探索、多样性和体验"],"一只拿着城市美食地图、面对多家新餐厅的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("WGKR","快递召唤师","Parcel Summoner","shopping",35,"minimum",[
      rule("physical_ecommerce_orders_30d",">=",10,"近30天实物网购订单不少于10笔"),rule("ecommerce_active_weeks_30d",">=",3,"近30天至少3周存在网购"),rule("ecommerce_share_variable_spend",">=",0.25,"实物网购占非固定生活消费不少于25%"),rule("ecommerce_product_categories_30d",">=",3,"覆盖至少3个商品类别"),rule("ecommerce_merchant_dispersion","multi",true,"存在多个不同商户或品牌订单")],
      ["综合电商","品牌线上商城","社交电商","服饰","家居","日用品","数码配件"],["网购高频","选择丰富","好物雷达","即时消费","线上消费派"],"网购频次和持续性 > 单纯金额",["可识别宠物用品优先MHZT","可识别食材优先MCDR","游戏实体商品不计KJZS"],"高频实物网购 × 持续下单 × 多品类 × 多订单","网购是熟练的生活补给系统：挑选、比价、领券，再等包裹陆续上门。","Online shopping is a practiced supply system: browse, compare, claim a deal, and wait for the world to arrive at your door.",["世界那么大，你选择让它包邮到家。"],["The world is huge. You prefer it delivered."],["购物狂","购物成瘾","剁手党","败家","乱花钱","物质主义"],["不从高频网购判断成瘾或冲动","不默认商品无用","不推断收入性别职业","可以调侃购物车、凑单和快递通知"],"一只像魔法师一样召唤许多快递包裹的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("MCDR","菜场理财家","Market Money Manager","food",42,"minimum",[
      rule("ingredient_purchase_count_30d",">=",8,"近30天食材消费不少于8次"),rule("ingredient_active_weeks_30d",">=",3,"近30天至少3周出现食材采购"),rule("ingredient_share_dining",">=",0.3,"食材支出占餐饮相关支出不少于30%"),rule("ingredient_categories_30d",">=",3,"蔬果、肉类、蛋奶、粮油等覆盖至少3类"),rule("ingredient_vs_delivery_frequency",">",1,"食材采购频次明显高于外卖")],
      ["菜市场","生鲜超市","水果店","肉禽蛋奶","粮油调味","线上生鲜"],["精打细算","烟火气十足","计划消费","性价比导向","生活掌控感"],"购买频次和持续性 > 单次金额",["线上购买食材仍优先本人格而非WGKR","与BKHZ可分别计算，但以食材和外卖相对频次区分"],"高频食材采购 × 持续性 × 品类丰富 × 较低外卖依赖","账单里是日常烟火：会买、会挑、会安排，是把日子过好的生活能力。","Your spending is full of everyday life. Knowing what to buy, how to choose, and how to plan is a skill of its own.",["不是舍不得花，是每一块钱都要花得明白。"],["Not cheap. Just making every dollar count."],["抠门","小气","穷","买不起","爱占便宜","家庭主妇","家庭煮夫"],["不把性价比描述为抠门","不推断收入、性别、婚姻或家庭角色","不默认本人每天做饭","突出规划、生活感和掌控感"],"一只在菜市场认真挑选蔬果并核对价格的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("JZZY","精致主义者","Refined Living Curator","lifestyle",32,"minimum",[
      rule("quality_lifestyle_count_30d",">=",6,"近30天品质或个人形象类消费不少于6次"),rule("quality_lifestyle_share",">=",0.2,"占非固定生活支出不少于20%"),rule("quality_lifestyle_categories_30d",">=",3,"覆盖至少3个相关类别"),rule("quality_lifestyle_active_weeks_30d",">=",3,"近30天至少3周出现相关消费"),rule("personal_care_service_count_30d",">=",2,"个人护理服务不少于2次，或与实物品质消费同时出现")],
      ["护肤","美妆","香氛","服饰","饰品","美发","美甲","美容护理","设计家居"],["品质导向","注重细节","悦己消费","审美在线","体验优先"],"类别丰富、持续性和品质生活占比 > 单件价格",["WGKR强调渠道和频次，本人格强调商品服务属性","家庭食材即使精品仍优先MCDR"],"品质与形象消费 × 多类别 × 持续性 × 体验导向","你愿意为生活质感买单，精致不是昂贵，而是在能力范围内认真选择喜欢的生活方式。","You pay attention to quality, design, and experience. Refinement is not about price; it is about choosing a life that feels considered.",["钱可以少花，但生活不能将就。"],["Spend less? Maybe. Settle for less? Never."],["虚荣","攀比","物质","拜金","败家","装精致","奢侈","消费主义"],["不推断虚荣、收入、阶层或性别","不把精致与名牌奢侈直接绑定","不默认为了他人认可","突出审美、品质、细节和体验"],"一只被香水、服饰、护肤品和设计小物围绕的优雅猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("DYSJ","订阅收藏家","Subscription Collector","digital",34,"minimum",[
      rule("active_subscriptions_30d",">=",5,"近30天识别到至少5个订阅服务"),rule("subscription_periodicity","recurring",true,"同一商户存在月度、季度或年度规律扣费"),rule("subscription_categories",">=",3,"订阅覆盖至少3个类别"),rule("subscriptions_three_cycles",">=",3,"至少3项订阅连续扣费3个周期"),rule("subscription_share_digital",">=",0.4,"订阅支出占数字服务相关消费不少于40%")],
      ["影音会员","音乐会员","云存储","软件订阅","AI工具","阅读会员","学习平台","生活服务会员"],["数字生活派","固定续费","便利导向","会员常驻","小额高频"],"活跃订阅数量、周期性、持续性 > 总金额",["可明确识别的游戏会员、战令和月卡优先KJZS"],"多项活跃订阅 × 周期扣费 × 长期持续 × 多类别","快乐藏在自动续费里，Premium让数字生活少一点限制、多一点顺手。","Your happiness often hides in little auto-renewals. Premium services make digital life smoother and less restricted.",["每笔都是小钱，每月都是固定见面。"],["Small charges. Same faces. Every month."],["冤大头","忘记取消","白花钱","被割韭菜","交智商税","自动扣费受害者"],["不默认忘记取消或没有使用","不判断订阅是否值得","不推断收入或管理能力","可轻松调侃Premium和自动续费"],"一只被会员卡、播放图标、云盘和自动续费收据包围的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("KJZS","氪金战士","Top-Up Warrior","digital",46,"minimum",[
      rule("game_payment_count_30d",">=",5,"近30天游戏充值或内购不少于5次"),rule("game_payment_active_weeks_30d",">=",3,"近30天至少3周出现游戏付费"),rule("game_share_entertainment",">=",0.3,"游戏支出占娱乐消费不少于30%"),rule("same_game_payment_count_30d",">=",3,"同一游戏或平台不少于3笔付费"),rule("virtual_game_content_repeated","repeated",true,"多次出现点券、皮肤、角色或通行证等虚拟内容")],
      ["手游充值","PC游戏内购","虚拟货币","皮肤","角色","装备","Battle Pass","游戏月卡"],["游戏热爱","虚拟消费","限定敏感","体验投入","快乐充值"],"游戏内付费频次、持续性、娱乐占比 > 单次金额",["明确游戏服务优先于DYSJ","手柄、主机、实体卡带等实物不直接视为氪金"],"游戏虚拟消费 × 高频充值 × 持续性 × 娱乐占比","游戏是值得认真投入的快乐主场，你愿意为角色、装备和体验买单。","Gaming is a place worth investing some fun money in, from skins and passes to characters and experiences.",["嘴上说着零氪，账单从不配合。"],["You say “free to play.” Your bank statement says otherwise."],["游戏成瘾","网瘾","败家","乱充钱","沉迷游戏","不务正业","交智商税"],["不判断成瘾、沉迷或自制力","不贬低虚拟商品价值","不推断收入性别年龄职业","突出游戏兴趣和体验付费"],"一只战斗姿态的猫被游戏皮肤、点券和通行证围绕，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("SZJZ","地球 online 玩家","Earth Online Player","travel",36,"minimum",[
      rule("independent_travel_cycles_90d",">=",2,"近90天至少2次独立旅行周期"),rule("travel_categories_90d",">=",3,"交通、住宿、门票活动、当地出行覆盖至少3类"),rule("travel_share_variable_spend_90d",">=",0.15,"旅行支出占非固定生活消费不少于15%"),rule("linked_travel_chain_categories",">=",2,"同一周期出现长途交通加住宿或景点体验等至少2类"),rule("non_home_regions_90d",">=",2,"识别到至少2个不同于日常消费地的城市或地区")],
      ["机票","长途铁路","酒店民宿","旅行平台","景区门票","当地交通","跨境交通","旅行体验"],["旅行优先","体验导向","地图拓展","出行消费","探索欲在线"],"旅行周期、多类别消费链、跨地区 > 单笔金额",["日常城市内重复移动属于TQDG","餐厅探索仍可计TDJ","无法识别旅行目的时用中性表达"],"多次旅行 × 跨地区消费 × 旅行消费链 × 多类别体验","你把预算留给远方，机票、酒店和门票把世界装进生活。","Travel adds new coordinates to life. Flights, hotels, and tickets turn spending into new views and stories.",["把钱花在路上，把世界装进生活。"],["Spend on the journey. Collect the world."],["乱花钱","不会存钱","月光","炫富","不务正业","旅游上瘾","享乐主义"],["不推断收入财富或家庭背景","不默认旅行目的是休闲或逃避现实","不从地点推断职业国籍住址","用出行、探索、体验等中性表达"],"一只拿着行李箱、登机牌和地图探索新坐标的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("TQDG","通勤永动机","Perpetual Commuter","transport",41,"minimum",[
      rule("city_transport_count_30d",">=",20,"近30天城市交通消费不少于20笔"),rule("city_transport_active_weeks_30d",">=",4,"至少4周均出现城市交通"),rule("city_transport_weekly_average",">=",5,"平均每周不少于5次"),rule("city_transport_share_variable",">=",0.1,"占日常可变支出不少于10%"),rule("city_transport_modes",">=",2,"覆盖至少2类交通方式"),rule("weekday_route_regularity","present",true,"工作日或上课日存在重复规律交通记录")],
      ["地铁","公交","交通卡","出租车","网约车","共享单车","城市轮渡"],["高频出行","城市穿梭","交通常驻","日常刚需","移动在线"],"高频 × 持续 × 日常规律 > 总金额",["日常城市移动与SZJZ的非日常跨地区移动区分","旅行期间当地交通应降低通勤权重"],"高频城市交通 × 长期持续 × 日常规律 × 非旅行场景","生活半径靠一程又一程撑起来，账单直接记录每天跑了多远。","Your daily life stays in motion through metros, buses, rides, and shared bikes; your statement counts the trips.",["每天都在赶路，余额也跟着刷步数。"],["Always on the move. So is your money."],["打工人","社畜","牛马","命苦","没车","买不起车","通勤痛苦"],["不推断职业学生身份、车辆或经济条件","不默认移动意味着压力或长通勤","不生成具体住址工作地等敏感位置","突出高频持续规律移动"],"一只穿梭在地铁、公交和共享单车之间的猫，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("JW","卷王","Page Chewer","learning",50,"any",[
      rule("learning_share_total",">=",0.2,"教育学习占总消费不少于20%，且月度学习交易不少于5笔或学习支出为前三",{and:[{metric:"learning_transactions_month",operator:">=",value:5},{metric:"learning_rank",operator:"<=",value:3}],andMode:"any"}),rule("learning_books_supplies_share",">=",0.3,"教育培训、书籍和学习用品占比不少于30%，且有效交易大于3笔",{and:[{metric:"valid_transactions",operator:">",value:3}]}),rule("early_transactions_05_08_month",">=",15,"5:00至8:00消费不少于15笔，且学习教育支出至少5笔",{and:[{metric:"learning_transactions_month",operator:">=",value:5}]})],
      ["教育培训","书籍教材","文具学习用品","在线课程","考试报名","学习工具","知识付费","早间学习消费"],["自我投资","知识付费","学习型消费","目标导向","精神食粮充足"],"学习支出占比、有效交易量和早间学习信号",["仅早起而无学习消费不可判定"],"高学习投入或高学习占比，结合有效交易；早间规则需同时具备学习消费","账单像持续更新的培养计划，课程、书籍和工具都在给未来的自己加技能点。","Your statement looks like an ongoing self-upgrade plan, serving books, courses, and study tools as breakfast for the brain.",["别人在消费，你在投资自己。","把头往书里一埋就开始大吃特吃。"],["PAGE CHEWER","ALL YOU CAN READ. ALL YOU CAN EAT.","Professional Knowledge Chewer."],["书呆子","内卷","没用"],["不贬低学习投入","不把努力描述为病态竞争","不推断学历、职业或能力"],"一只戴眼镜、埋头书堆并吃书本汉堡的猫，桌上亮着台灯，复古网点印刷风格。"),
    make("HAO","壕","Black Card Roller","amount",55,"all",[
      rule("median_transaction_amount_cny",">=",70,"单笔消费金额中位数不少于70元"),rule("large_purchase_share",">=",0.4,"大额消费占比不少于40%"),rule("top_category","in",["网购","美妆服饰","堂食"],"最大消费类别属于网购、美妆服饰或堂食"),rule("monthly_transactions",">=",10,"月度消费不少于10笔")],
      ["高客单堂食","美妆服饰","奢侈品","数码产品","娱乐体验","旅行","持续高客单消费"],["高客单价","大额消费","价格钝感","品质优先","出手阔绰"],"稀有人格，严格要求全部条件同时满足",["单次昂贵购买不足以判定，必须是持续账单结构"],"高交易中位数 × 高大额占比 × 指定主类别 × 足够交易量","价格标签更像注释，账单里一笔接一笔都保持高客单水准。","Your spending keeps landing in a high-ticket range, swipe after swipe; the price tag feels more like a footnote.",["银行卡余额里零多到数不清。","今天全场消费我买单。"],["JUST SWIPE.","PRICE IS JUST A NUMBER.","ONLY BLACK CARD."],["败家","乱花钱"],["不推断收入财富或阶层","不把高客单描述为浪费","不把单次购买夸大为稳定人格"],"一只戴皇冠、坐在购物袋与高价物品上的猫，复古网点印刷风格。"),
    make("SCTZ","散财童子","Small-Bill Sprinkler","amount",30,"any",[
      rule("daily_average_transactions",">=",3,"平均每天交易不少于3笔",{and:[{metric:"small_transaction_share",operator:">=",value:0.6},{metric:"top_category_share",operator:"<",value:0.3}]}),rule("transactions_under_30_share",">=",0.5,"低于30元的交易占比不少于50%")],
      ["便利店","咖啡奶茶","小吃零食","公共交通","打车","日用品","小额网购","扫码支付"],["小额高频","随手支付","消费分散","积少成多","钱包漏水"],"小额频率和分散度",["某一具体类别高度集中时应优先对应类别人格"],"高频小额 × 高小额占比 × 低单类集中度","钱以十块、二十块、三十块一点点溜走，月底集合成一支完整的消费大军。","Money slips away in small, harmless-looking charges that turn into a surprisingly organized crowd by month-end.",["钱像水一样流走了！","鄙人平日无甚爱好，唯爱花点小钱。"],["SMALL BILLS. BIG HOLE. WHERE DID IT GO?"],["没有自控力","月光族","穷"],["不判断自制力或经济状况","保持积少成多的轻松调侃","不把所有小额支出视为无用"],"一只走路时口袋不断掉出硬币的猫，复古网点印刷风格。"),
    make("SQDS","省钱大师","Savings Master","amount",44,"any",[
      rule("essentials_share",">=",0.6,"衣食住行等必需消费占比不少于60%",{and:[{metric:"median_transaction_amount_cny",operator:"<=",value:30},{metric:"large_nonessential_share",operator:"<=",value:0.15}]}),rule("daily_spend_cny","<=",50,"一周内连续3日每日消费不高于50元",{consecutiveDays:3}),rule("weekly_spend_excluding_fixed_cny","<=",350,"一个月内至少2周消费不高于350元，排除房租学费等",{minimumWeeks:2})],
      ["基础餐饮","公共交通","日常生活","基础服饰","房租","必要生活支出"],["必要优先","低客单价","预算意识","克制消费","安全感储备"],"必要支出结构、低客单和低非必需大额占比",["关注价格不等于MCDR；本规则观察整体账单结构"],"必要优先 × 低客单 × 低非必需大额 × 持续预算约束","每一笔最好都有理由，可有可无的东西要经过更严格的钱包审批。","Every purchase needs a reason. Essentials pass; optional wants face a much stricter review.",["理性消费，快乐加倍。","包里有粮心里不慌。"],["SAVE SMART. LIVE LARGE.","SAVE TODAY. RICHER TOMORROW."],["抠门","小气"],["不评价用户小气或匮乏","不推断收入财务压力","以佩服、鼓励和轻松调侃为主"],"一只满足地抱着存钱罐的猫，周边简约，复古网点印刷风格。"),
    make("YXDW","夜行动物","Night Owl","time",33,"any",[
      rule("night_transaction_share_21_05",">=",0.3,"21:00至05:00交易占比不少于30%，且月度交易大于10笔",{and:[{metric:"monthly_transactions",operator:">",value:10}]}),rule("night_transactions_month_21_05",">=",15,"月度夜间交易不少于15笔"),rule("night_transactions_day_21_05",">=",3,"单日夜间交易不少于3笔")],
      ["深夜外卖","夜宵","打车","网购","便利店","娱乐"],["深夜活跃","昼伏夜出","夜间消费","睡前下单","凌晨自由"],"21:00至05:00的交易占比或笔数",["夜间类别仍可同时贡献具体消费人格，但本规则强调时间"],"高夜间占比或高夜间笔数","晚上九点以后钱包进入黄金时段，别人结束一天时，你的消费记录可能才刚开始。","After 9 p.m., your wallet enters prime time. While others wrap up the day, your transaction history is getting started.",["凌晨花的钱不是钱，是自由。","凌晨，猎杀时刻！"],["OPEN 24/7. ESPECIALLY 2AM.","NIGHT OWL. NIGHT ORDER."],["熬夜伤身","失眠"],["不做健康或睡眠判断","不推断工作和作息原因","保持神秘、夜话式轻松口吻"],"一只夜里躺在床上拿手机消费、双眼发亮的猫，窗外有月亮，复古网点印刷风格。"),
    make("YDDJ","月底渡劫人","End-of-Month Survivor","rhythm",48,"all",[
      rule("first_10_days_spend_share",">=",0.5,"月度前10天消费占全月不少于50%"),rule("last_10_vs_first_10_spend","<=",0.5,"最后10天消费不高于前10天的50%"),rule("first_10_valid_spend_days",">=",5,"前10天至少5个有效消费日"),rule("last_10_valid_spend_days",">=",5,"最后10天至少5个有效消费日")],
      ["不限具体类别","同一周期前高后低消费节奏"],["前松后紧","月初豪爽","月底收手","消费前置","周期性吃土"],"前10天与最后10天的显著消费节奏差，且两段数据均充分",["有效消费日门槛用于避免账单缺失误判","不得把节奏推断为贫困或工资耗尽"],"前10天高占比 × 末10天显著回落 × 两段有效日充分","一个月像两个经济周期：月初JUST SWIPE，月底JUST SURVIVE，苦中作乐但不指向真实困境。","Your month runs on two economies: free-flowing at the start, suddenly restrained at the end, without implying hardship.",["月初花钱靠心情，月底活着看命。","月底最大的消费项目：忍住。"],["STARTED WITH “SWIPE.” ENDED WITH “I’M FINE.”","Month begin: JUST SWIPE. Month end: JUST SURVIVE."],["穷","没钱","月光族","财务状况差","入不敷出","工资花完了"],["不把前高后低解释为贫困、财务危机或工资耗尽","保持苦中作乐和自嘲","必须确认前后各至少5个有效消费日"],"一只猫坐在只剩几枚硬币的钱包旁数日历，月初刷卡画面形成轻松反差，不表现真实贫困。"),
    make("MHZT","毛孩子提款机","Furry Kid ATM","lifestyle",47,"minimum",[
      rule("pet_transactions_30d",">=",5,"近30天宠物相关消费不少于5笔"),rule("pet_active_weeks_30d",">=",3,"近30天至少3周出现宠物消费"),rule("pet_categories_30d",">=",2,"食品、日用品、医疗、护理、服务覆盖至少2类"),rule("pet_share_variable_spend",">=",0.1,"宠物支出占非固定生活支出不少于10%"),rule("same_pet_merchant_count_30d",">=",2,"同一宠物商户近30天重复消费不少于2次"),rule("pet_active_months_history",">=",3,"历史账单连续至少3个月有宠物消费")],
      ["宠物食品","猫粮狗粮","零食","猫砂","日用品","玩具","洗护美容","宠物医院","保险","寄养"],["宠爱在线","长期投入","口粮常备","有求必应","毛孩子优先"],"持续性、频次和多场景 > 单次金额",["电商购买可识别宠物用品优先本规则而非WGKR","单次高额医疗不能单独判定","信息不足不猜宠物种类"],"持续宠物消费 × 高频补给 × 多场景覆盖 × 重复购买","账单里住着一个零收入、稳定消费的角色，口粮、玩具、护理和医疗构成温暖的日常照护。","A furry household member has zero income but steady spending: food, care, toys, and health form a warm, consistent routine.",["你负责赚钱，它负责花钱。"],["You make the money. They spend it."],["猫奴","狗奴","宠物奴","败家","烧钱","吞金兽","碎钞机","养不起","过度溺爱"],["不判断溺爱或不理性","不贬低医疗支出","不默认压缩本人基本需求","不推断宠物种类、家庭结构、职业或收入"],"一只猫围绕宠物食品、医疗、护理和玩具消费转盘，复古网点印刷风格。",{minimumMatchedRules:3}),
    make("RQWL","社交能手","Social Connector","special",90,"all",[
      rule("social_transfers_and_red_packets",">=",10,"统计周期内转账和红包记录不少于10笔"),rule("exclude_social_flows_from_spending_total","=",true,"这些转账和红包不计入消费总额")],
      ["好友转账","AA收付款","红包","代付","聚餐结算","随礼","活动分摊"],["社交活跃","转账频繁","AA熟练","人情往来","朋友圈结算中心"],"社交资金往来笔数；触发后覆盖普通人格",["社交资金流不计入消费总额"],"转账红包 ≥ 10笔，作为Special Persona优先覆盖","账单里有一张社交关系网，垫付、AA、红包和结算总能和某个人联系起来。","Your transaction history maps a social network of shared bills, red packets, favors, and friendly settlements.",["钱是流动的，人情也是。","就爱给朋友花点小钱。"],["FRIENDS FIRST. BILLS LATER.","SOCIAL CAPITAL PAID."],["冤大头","被薅","借钱不还"],["不评价人际关系质量","不推断被占便宜或债务问题","保持温情、略带调侃"],"一只正在给一圈猫朋友发红包的猫，复古网点印刷风格。",{override:true,specialPersona:true}),
    make("ZYX","一店死侍","One-Store Loyalist","special",88,"any",[
      rule("top_merchant_transaction_share",">=",0.5,"同一商户交易笔数占全部交易不少于50%，且有效交易不少于20笔",{and:[{metric:"valid_transactions",operator:">=",value:20}]}),rule("same_merchant_transactions_day",">=",4,"单日同一商家消费不少于4笔"),rule("same_merchant_daily_count",">=",2,"连续至少3天每日同一商户不少于2笔",{consecutiveDays:3}),rule("same_merchant_transactions_month",">=",30,"每月同一商家不少于30笔，排除外卖平台统一商户名")],
      ["同一咖啡店","奶茶店","餐厅","便利店","超市","品牌门店","电商店铺"],["超高复购","商户忠诚","固定选择","拒绝变心","长期关系"],"同一真实商户的高占比和持续复购",["排除外卖平台名称统一导致的伪单一商户","具体品类人格可同时得分，但Special Persona触发后优先"],"高商户集中度或极高连续复购","世界上店很多，钱包偏偏只对一家长情，这不是重复消费，是commitment。","Countless stores exist, yet your wallet keeps choosing the same one. This is not repetition; it is a relationship.",["弱水三千，只刷一家。"],["ONE STORE. ONE HEART.","LOYALTY LEVEL: MAX.","TILL RECEIPTS DO US PART."],["单调","没得选","傻"],["不把忠诚描述为缺乏选择","必须识别真实商户并排除平台聚合名","使用深情、告白式表达"],"一只紧紧抱着商店招牌、周围飘着爱心的猫，复古网点印刷风格。",{override:true,specialPersona:true}),
    make("LBX","端水大师","Balance Master","fallback",5,"all",[
      rule("other_persona_matches","=",0,"没有命中其他人格规则"),rule("top_category_share","<",0.3,"最大单一消费类别占总消费金额低于30%")],
      ["餐饮","购物","交通","娱乐","生鲜","饮品","日用","学习"],["雨露均沾","类别均衡","兴趣广泛","拒绝偏科","消费多面手"],"无其他命中且没有主导类别",["只能在普通和Special人格均未命中时使用"],"无其他人格命中 × 最大类别占比 < 30%","每个类别都被照顾得周到，谁都分到一点，但谁也别想独占钱包。","Every category gets a fair share, but none takes over. Your spending refuses to pick a single favorite.",["什么都花一点，什么都不上头。"],["BALANCED. MOSTLY.","A LITTLE OF EVERYTHING."],["平庸","没特点","无聊"],["不把均衡描述为平庸或无聊","只作为规则兜底","保持平和、总结式语气"],"一只像章鱼一样同时拿着咖啡、购物袋、地铁卡和游戏手柄的猫，复古网点印刷风格。",{fallback:true}),
    make("SMR","数据无法捕获之人","Data Escapee","fallback",100,"any",[
      rule("valid_transactions","<",10,"有效交易少于10笔"),rule("covered_categories","<",3,"消费覆盖少于3个类别"),rule("data_period_sufficient","=",false,"统计周期过短或数据完整度不足")],
      ["有效交易不足","类别覆盖不足","统计周期过短","可识别习惯数据不足"],["数据稀少","难以定义","拒绝被捕获","暂时隐身"],"先于其他人格检查数据充足度；数据不足时不做人格推断",["原神秘人已明确改为数据不足兜底，不表达神秘消费倾向","样例4笔有效交易不足，可靠判断至少需10笔且覆盖3类"],"有效交易 < 10 或类别 < 3 或数据周期不足","不是没有消费人格，只是账单还不够了解你；算法明确承认数据边界。","You do have a spending personality; this statement simply does not contain enough evidence to classify it reliably.",["账单太薄，看不透你。"],["NOT ENOUGH DATA. YET.","COME BACK WITH MORE."],["没钱","不消费","可疑"],["不把数据不足描述为贫穷、不消费或可疑","不从少量交易推断任何人格","明确邀请提供更完整账单"],"一只穿风衣、戴墨镜、拿放大镜检查短收据的侦探猫，复古网点印刷风格。",{fallback:true,override:true,dataSufficiencyFallback:true})
  ];
})();
